# Site settings
title: Junia Marketing Projects
email:
description: >  # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown


domain: raulghiurau.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://raulghiurau.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /junia/      # place folder name if the site is served in a subfolder
