# config.yml
backend:
  name: github
  repo: raulghiurau/junia # Path to your GitHub repository

# This line should *not* be indented
publish_mode: editorial_workflow

media_folder: "img/assets"
public-folder: "uploads"

collections:
  - name: 'blog'
    label: 'Professional'
    folder: '_posts/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { lable: 'Author', name: 'author', widget: 'string' }
      - { lable: 'Duration', name: 'duration', widget: 'string' }
      - { 
          label: 'Category', 
          name: 'category', 
          widget: 'dropdown', 
          options: 
            [
              { label: 'Blog', value: 'blog' },
              { label: 'Marketing', value: 'Marketing' },
              { label: 'World', value: 'world' },
              { label: 'Technology', value: 'technology' },
              { label: 'Lifestyle', value: 'lifestyle' }
            ],
          default: 'blog'
        }
      - { lable: 'Category', name: 'category', widget: 'string', default: 'blog' }
      - { lable: 'Tags', name: 'tags', widget: 'string' }
      - { lable: 'Image  650 x 350', name: 'image', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'client'
    label: 'Clients'
    folder: '_posts/clients'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'client' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Project Date', name: 'project-date', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { lable: 'Services', name: 'services', widget: 'string' }
      - { lable: 'Category', name: 'category', widget: 'string', default: 'client' }
      - { lable: 'Website', name: 'website', widget: 'string' }
      - { lable: 'Image Logo', name: 'image', widget: 'image', required: false }
      - { lable: 'Background Image', name: 'background-image', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }